In [2]:
# Scientific libraries
              
import numpy as np              
import scipy as sp              
import pandas as pd              
import json              
import missingno as msno              

# Loading Plotting Modules
              
import matplotlib              
import matplotlib.pyplot as plt              
import seaborn as sns              
%matplotlib inline              
import chart_studio.plotly as py              
import plotly.figure_factory as ff              
import plotly.graph_objects as go              
import plotly.express as px              
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot              
init_notebook_mode(connected=True)              

# Setting Data Frame Options
              
pd.set_option('display.max_rows', 40)              
pd.set_option('display.max_columns', 50)              
pd.set_option('display.width', 100)              
pd.set_option('display.max_colwidth', 100)              

# Setting Plot Configuration
              
sns.set(rc={'figure.figsize':(19,11)}, style = 'white')              

import katana.nbutil as ktn
              
import os

In [59]:
df = pd.read_parquet('./output/pre-modeling/all_num_data.pqt.gz')  
m, n = df.shape
print('Data Frame: {} x {}'.format(m,n))                
df.head()

Data Frame: 1097231 x 384

,C1,C10,C11,C12,C13,C14,C2,C3,C4,C5,C6,C7,C8,C9,D1,D10,D11,D12,D13,D14,D15,D2,D3,D4,D5,...,V9,V90,V91,V92,V93,V94,V95,V96,V97,V98,V99,dist1,dist2,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,id_10,id_11,isFraud
TransactionID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2987000,1.0,0.0,2.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,14.0,13.0,13.0,NaN,NaN,NaN,0.0,NaN,13.0,NaN,NaN,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2987001,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2987002,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,315.0,NaN,NaN,NaN,315.0,NaN,NaN,0.0,NaN,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,287.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2987003,2.0,0.0,1.0,0.0,25.0,1.0,5.0,0.0,0.0,0.0,4.0,0.0,0.0,1.0,112.0,84.0,NaN,NaN,NaN,NaN,111.0,112.0,0.0,94.0,0.0,...,NaN,0.0,0.0,0.0,0.0,0.0,1.0,48.0,28.0,0.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2987004,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,70787.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,0.0

In [61]:
y = df.isFraud
df.drop(['isFraud', 'TransactionDT'], axis=1, inplace=True)
cols = df.columns

In [7]:
desc = df.describe()

,C1,C10,C11,C12,C13,C14,C2,C3,C4,C5,C6,C7,C8,C9,D1,D10,D11,D12,D13,D14,D15,D2,D3,D4,D5,...,V89,V9,V90,V91,V92,V93,V94,V95,V96,V97,V98,V99,dist1,dist2,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,id_10,id_11
count,1.097228e+06,1.097228e+06,1.097228e+06,1.097228e+06,1.092483e+06,1.097228e+06,1.097228e+06,1.097228e+06,1.097228e+06,1.097228e+06,1.097228e+06,1.097228e+06,1.097228e+06,1.097228e+06,1.089931e+06,1.008664e+06,641426.000000,133971.000000,185336.000000,177381.000000,996049.000000,581665.000000,631211.000000,851458.000000,563015.000000,...,995986.000000,641426.000000,995986.000000,995986.000000,995986.000000,995986.000000,995986.000000,1.096917e+06,1.096917e+06,1.096917e+06,1.096917e+06,1.096917e+06,453743.000000,74063.000000,286140.000000,277848.000000,132805.000000,132805.000000,271615.000000,271615.000000,10214.000000,10214.000000,149264.000000,149264.000000,277756.000000
mean,1.224565e+01,3.656317e+00,8.968402e+00,3.417374e+00,3.036952e+01,7.274049e+00,1.316624e+01,1.569227e-02,3.304229e+00,5.290377e+00,8.047716e+00,2.308044e+00,3.643492e+00,4.541059e+00,1.007141e+02,1.415345e+02,183.577017,66.116518,18.117435,58.009370,185.152096,178.493856,30.772553,157.700888,46.669268,...,0.011762,1.040678,0.371615,0.388852,0.204722,0.210371,0.144801,6.655599e-01,2.252885e+00,1.170536e+00,5.992796e-02,9.157712e-01,103.573384,234.472463,-10.743423,183561.864433,0.056594,-0.073213,1.432248,-6.750861,12.892990,-37.598590,0.083650,-0.273609,99.748058
std,1.118594e+02,7.196617e+01,8.079689e+01,7.340473e+01,1.172570e+02,4.114092e+01,1.285684e+02,1.904406e-01,5.800246e+01,2.563929e+01,6.135191e+01,5.209126e+01,7.231599e+01,1.894261e+01,1.669482e+02,2.137367e+02,225.954099,153.782459,74.744808,154.868172,239.163890,187.068316,72.831084,223.712055,103.980714,...,0.109478,0.226259,0.506327,0.549215,0.423312,0.449187,0.351952,1.544572e+01,2.964145e+01,2.036026e+01,2.792181e-01,2.589497e+00,346.012876,542.707593,14.439337,171590.837001,0.642900,0.774036,5.165387,16.211056,11.536998,25.837035,0.996821,2.479115,1.123778
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-53.000000,-83.000000,0.000000,-193.000000,-83.000000,0.000000,0.000000,-122.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,-100.000000,1.000000,-13.000000,-28.000000,-81.000000,-100.000000,-46.000000,-100.000000,-36.000000,-100.000000,90.000000
25%,1.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,26.000000,1.000000,0.000000,1.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.000000,7.000000,-10.000000,65946.500000,0.000000,0.000000,0.000000,-6.000000,4.000000,-47.000000,0.000000,0.000000,100.000000
50%,1.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,3.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,4.000000e+00,1.300000e+01,69.000000,0.000000,0.000000,0.000000,50.000000,104.000000,8.000000,23.000000,9.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.000000,41.000000,-5.000000,129158.500000,0.000000,0.000000,0.000000,0.000000,13.000000,-34.000000,0.000000,0.000000,100.000000
75%,3.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,1.300000e+01,2.000000e+00,3.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,2.000000e+00,0.000000e+00,1.000000e+00,2.000000e+00,1.330000e+02,2.240000e+02,333.000000,18.000000,0.000000,0.000000,341.000000,290.000000,27.000000,272.000000,33.000000,...,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,22.000000,201.000000,-5.000000,245795.250000,0.000000,0.000000,1.000000,0.000000,21.000000,-23.000000,0.000000,0.000000,100.000000
max,4.685000e+03,3.257000e+03,3.188000e+03,3.188000e+03,2.918000e+03,1.429000e+03,5.691000e+03,3.100000e+01,2.253000e+03,3.760000e+02,2.253000e+03,2.255000e+03,3.331000e+03,5.720000e+02,6.410000e+02,1.091000e+03,883.000000,879.000000,1066.000000,1085.000000,1091.000000,641.000000,1076.000000,1091.000000,1088.000000,...,7.000000,11.000000,5.000000,8.000000,7.000000,7.000000,2.000000,8.800000e+02,1.410000e+03,9.760000e+02,1.200000e+01,8.800000e+01,10286.000000,11623.000000,0.000000,999869.000000,11.000000,0.000000,52.000000,0.000000,61.000000,0.000000,25.000000,0.000000,100.000000

In [62]:
log_cols = (cols[(cols.str.contains('C'))|(cols.str.contains('dist'))|(cols.str.contains('Transaction'))]).tolist()

In [63]:
std_cols = list(set(df.columns.tolist()) - set(log_cols))

In [64]:
log_cols, std_cols

(['C1',
  'C10',
  'C11',
  'C12',
  'C13',
  'C14',
  'C2',
  'C3',
  'C4',
  'C5',
  'C6',
  'C7',
  'C8',
  'C9',
  'TransactionAmt',
  'dist1',
  'dist2'],
 ['V263',
  'V217',
  'V110',
  'V188',
  'V154',
  'V220',
  'V332',
  'V174',
  'V333',
  'V229',
  'V181',
  'D14',
  'V17',
  'V8',
  'V200',
  'V194',
  'V32',
  'V130',
  'V119',
  'V81',
  'V297',
  'V295',
  'V93',
  'id_03',
  'D7',
  'V289',
  'V85',
  'V62',
  'V326',
  'V279',
  'D11',
  'V39',
  'V250',
  'D12',
  'V3',
  'V38',
  'V73',
  'V74',
  'V242',
  'V285',
  'V328',
  'V272',
  'V183',
  'V216',
  'V87',
  'V80',
  'V90',
  'V184',
  'V161',
  'V165',
  'V12',
  'V64',
  'V243',
  'V52',
  'V103',
  'V79',
  'V287',
  'V45',
  'V221',
  'V248',
  'V198',
  'V14',
  'V265',
  'V262',
  'V129',
  'V36',
  'V166',
  'V339',
  'V301',
  'V41',
  'id_11',
  'V13',
  'V211',
  'V124',
  'V189',
  'V234',
  'V158',
  'id_01',
  'V292',
  'id_04',
  'V203',
  'V26',
  'V327',
  'V134',
  'V172',
  'V163',
  'V95',
  'V140',
  'V148',
  'V288',
  'V5',
  'D4',
  'V207',
  'V246',
  'id_06',
  'V197',
  'V281',
  'V23',
  'V156',
  'V247',
  'V71',
  'V25',
  'V290',
  'V10',
  'V320',
  'V226',
  'V235',
  'V302',
  'V206',
  'V55',
  'V16',
  'V231',
  'V323',
  'V58',
  'V107',
  'V97',
  'V337',
  'V192',
  'V123',
  'V175',
  'V70',
  'V157',
  'V94',
  'V102',
  'V59',
  'V88',
  'V336',
  'V205',
  'V75',
  'V241',
  'V315',
  'V255',
  'V51',
  'V1',
  'V273',
  'V7',
  'V132',
  'V236',
  'V258',
  'V126',
  'V214',
  'V77',
  'V164',
  'V152',
  'V50',
  'V311',
  'V319',
  'D2',
  'V202',
  'V30',
  'V105',
  'V223',
  'V67',
  'V11',
  'V271',
  'V9',
  'D1',
  'V142',
  'V204',
  'V136',
  'V44',
  'V185',
  'V169',
  'V4',
  'V116',
  'V111',
  'V324',
  'id_07',
  'V318',
  'V294',
  'V304',
  'V233',
  'V2',
  'V186',
  'V54',
  'V276',
  'V24',
  'V283',
  'V29',
  'V114',
  'V312',
  'V317',
  'V86',
  'V213',
  'V40',
  'V20',
  'V138',
  'V291',
  'D3',
  'V135',
  'V306',
  'V331',
  'D13',
  'id_02',
  'V321',
  'V99',
  'V227',
  'D15',
  'V173',
  'V69',
  'V308',
  'V35',
  'V33',
  'V19',
  'V212',
  'V113',
  'V182',
  'V244',
  'V82',
  'V253',
  'V170',
  'V96',
  'V296',
  'D8',
  'V260',
  'V125',
  'D9',
  'V293',
  'V313',
  'V76',
  'V314',
  'V15',
  'V252',
  'V264',
  'V167',
  'V310',
  'V284',
  'V299',
  'V27',
  'V104',
  'V210',
  'V118',
  'V256',
  'V257',
  'V168',
  'V228',
  'V128',
  'V179',
  'V329',
  'V53',
  'V61',
  'V225',
  'V325',
  'V159',
  'V259',
  'V303',
  'V63',
  'V150',
  'V232',
  'V338',
  'V162',
  'V145',
  'V237',
  'V78',
  'V98',
  'V280',
  'V254',
  'V151',
  'V268',
  'V240',
  'V91',
  'V139',
  'V222',
  'V187',
  'V309',
  'V239',
  'V201',
  'V275',
  'V83',
  'V141',
  'id_05',
  'V322',
  'V199',
  'V101',
  'id_09',
  'V144',
  'V66',
  'V37',
  'V106',
  'V21',
  'V146',
  'V209',
  'V143',
  'V316',
  'V133',
  'V305',
  'V277',
  'V28',
  'V307',
  'V224',
  'V251',
  'V249',
  'V176',
  'V208',
  'V278',
  'V48',
  'V171',
  'V131',
  'V238',
  'V230',
  'V274',
  'V190',
  'V178',
  'V121',
  'D6',
  'V215',
  'id_08',
  'V300',
  'V18',
  'V193',
  'V100',
  'V43',
  'V219',
  'V282',
  'V147',
  'V72',
  'V49',
  'V112',
  'V218',
  'V160',
  'V335',
  'V6',
  'V117',
  'D5',
  'V122',
  'V127',
  'V286',
  'V334',
  'V108',
  'V191',
  'V31',
  'V84',
  'V120',
  'V42',
  'V177',
  'V115',
  'V57',
  'V65',
  'V180',
  'V109',
  'V56',
  'V155',
  'V267',
  'D10',
  'V195',
  'V330',
  'V270',
  'V137',
  'V269',
  'V92',
  'V153',
  'V245',
  'V196',
  'V47',
  'V89',
  'V68',
  'V46',
  'V34',
  'V298',
  'V60',
  'V261',
  'id_10',
  'V22',
  'V149',
  'V266'])

In [65]:
from sklearn.preprocessing import StandardScaler

In [66]:
num_log_scl = df.loc[:,log_cols]
std_cols = df.loc[:,std_cols]
del df
gc.collect()

NameError: name 'gc' is not defined

In [71]:
scaler = StandardScaler()
num_std_scl = pd.DataFrame(scaler.fit_transform(std_cols))
num_std_scl.shape

(1097231, 365)

In [74]:
num_log_scl = num_log_scl.apply(np.log,axis=0)

In [73]:
num_log_scl.head()

,C1,C10,C11,C12,C13,C14,C2,C3,C4,C5,C6,C7,C8,C9,TransactionAmt,dist1,dist2
TransactionID,,,,,,,,,,,,,,,,,
2987000,1.0,0.0,2.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,68.5,19.0,NaN
2987001,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,29.0,NaN,NaN
2987002,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,59.0,287.0,NaN
2987003,2.0,0.0,1.0,0.0,25.0,1.0,5.0,0.0,0.0,0.0,4.0,0.0,0.0,1.0,50.0,NaN,NaN
2987004,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,50.0,NaN,NaN

In [80]:
num_log_scl.replace([np.inf,-np.inf], np.nan, inplace=True)
num_log_scl.head()

,C1,C10,C11,C12,C13,C14,C2,C3,C4,C5,C6,C7,C8,C9,TransactionAmt,dist1,dist2
TransactionID,,,,,,,,,,,,,,,,,
2987000,0.000000,NaN,0.693147,NaN,0.000000,0.0,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN,0.0,4.226834,2.944439,NaN
2987001,0.000000,NaN,0.000000,NaN,0.000000,0.0,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,3.367296,NaN,NaN
2987002,0.000000,NaN,0.000000,NaN,0.000000,0.0,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN,0.0,4.077537,5.659482,NaN
2987003,0.693147,NaN,0.000000,NaN,3.218876,0.0,1.609438,NaN,NaN,NaN,1.386294,NaN,NaN,0.0,3.912023,NaN,NaN
2987004,0.000000,0.0,0.000000,NaN,0.000000,0.0,0.000000,NaN,NaN,NaN,0.000000,NaN,0.0,NaN,3.912023,NaN,NaN

In [85]:
num_std_scl.columns = std_cols
num_std_scl.index = num_log_scl.index

In [86]:
num_std_scl.head()

,V263,V217,V110,V188,V154,V220,V332,V174,V333,V229,V181,D14,V17,V8,V200,V194,V32,V130,V119,V81,V297,V295,V93,id_03,D7,...,V56,V155,V267,D10,V195,V330,V270,V137,V269,V92,V153,V245,V196,V47,V89,V68,V46,V34,V298,V60,V261,id_10,V22,V149,V266
TransactionID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2987000,NaN,NaN,-0.087282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.466525,-0.139641,NaN,NaN,-0.467908,-0.215904,-0.028499,-0.422181,-0.128246,-0.046673,-0.468339,NaN,NaN,...,-0.184326,NaN,NaN,-0.601369,NaN,NaN,NaN,-0.047352,NaN,-0.48362,NaN,NaN,NaN,NaN,-0.10744,-0.107073,NaN,-0.404812,-0.097882,-0.431902,NaN,NaN,-0.45887,NaN,NaN
2987001,NaN,NaN,-0.087282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.466525,NaN,NaN,NaN,-0.467908,-0.215904,-0.028499,-0.422181,-0.128246,-0.046673,-0.468339,NaN,NaN,...,-0.184326,NaN,NaN,-0.662191,NaN,NaN,NaN,-0.047352,NaN,-0.48362,NaN,NaN,NaN,-0.163358,-0.10744,-0.107073,-0.129785,-0.404812,-0.097882,-0.431902,NaN,NaN,-0.45887,NaN,NaN
2987002,NaN,NaN,-0.087282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.466525,-0.139641,NaN,NaN,-0.467908,-0.215904,-0.028499,-0.422181,-0.128246,-0.046673,-0.468339,NaN,NaN,...,-0.184326,NaN,NaN,-0.662191,NaN,NaN,NaN,-0.047352,NaN,-0.48362,NaN,NaN,NaN,-0.163358,-0.10744,-0.107073,-0.129785,-0.404812,-0.097882,-0.431902,NaN,NaN,-0.45887,NaN,NaN
2987003,NaN,NaN,-0.087282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.466525,NaN,NaN,NaN,-0.467908,0.554656,-0.028499,-0.422181,-0.128246,1.210661,-0.468339,NaN,NaN,...,-0.184326,NaN,NaN,-0.269184,NaN,NaN,NaN,-0.047352,NaN,-0.48362,NaN,NaN,NaN,-0.163358,-0.10744,-0.107073,-0.129785,-0.404812,-0.097882,-0.431902,NaN,NaN,-0.45887,NaN,NaN
2987004,-0.032664,-0.124815,-0.087282,-0.007128,-1.458688,-0.137183,-0.084668,-0.33739,-0.077,-0.122914,-0.165541,NaN,NaN,NaN,-0.09019,0.194982,NaN,-0.215904,-0.028499,NaN,-0.128246,-0.046673,NaN,NaN,NaN,...,NaN,-1.378256,-0.050089,NaN,0.06637,-0.142498,-0.116429,-0.047352,-0.021133,NaN,-1.491363,0.097613,-0.070361,NaN,NaN,NaN,NaN,NaN,-0.097882,NaN,-0.0673,NaN,NaN,-1.340153,-0.0281

In [87]:
num_log_scl.shape, num_std_scl.shape

((1097231, 17), (1097231, 365))

In [88]:
all_num_data = num_log_scl.join(num_std_scl, how='left')

In [89]:
all_num_data.shape

(1097231, 382)

In [90]:
del num_log_scl, num_std_scl
gc.collect()

25468

In [91]:
all_num_data.to_parquet('./output/pre-modeling/all_num_processed.pqt.gz', compression='gzip')